// tslint:disable
/**
 * Tutorial Management API
 * This API exposes endpoints to manage reservations.
 *
 * OpenAPI spec version: 1.0
 * Contact: holidayacc@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
